import styles from "../styles/_home.module.scss";

import type { Metadata } from "next";
import { Monda, Outfit } from "next/font/google";
import Head from "next/head";

const monda = Monda({
  weight: ["400"],
  style: ["normal"],
  subsets: ["latin"],
});

const outfit = Outfit({
  weight: ["700"],
  style: ["normal"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pixel Forge Studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <Head>
        <link rel="icon" href="../public/images/pfs-logo.png" sizes="256x256"></link>
      </Head> */}
      <body className={`${outfit.className} ${styles.mainContainer}`}>
        {children}
      </body>
    </html>
  );
}
